project:
  type: website
  output-dir: ../public/site
  preview:
    port: 7777

website:
  title: 'origraph'
  site-url: https://www.origraph.net/site
  open-graph: true
  navbar:
    logo: 'logos/origraph/Logo Light Background.png'
    left:
      - text: About
        menu:
          - href: blog/about.qmd
            text: About the App
          - href: consulting.qmd
            text: Consulting
          - href: support.qmd
            text: Support
          - href: blog.qmd
            text: Blog
    right:
      - href: blog.xml
        text: '[![RSS Logo](/logos/social/rss.svg)[RSS Feed]{.navbar-logo-label}]{.navbar-logo-wrapper}'
      - href: https://patreon.com/Origraph
        text: '[![Patreon Logo](/logos/social/patreonWhite.png)[Patreon]{.navbar-logo-label}]{.navbar-logo-wrapper}'
      - href: app.qmd
        text: '[Launch App]{.origraph-button}'

format:
  html:
    theme:
      - minty
      - brand
    css:
      - quartoTweaks.css
      - built-library/origraph.css
    toc: true
