project:
  type: website
  output-dir: ../public/site
  preview:
    port: 7777
    browser: false
    navigate: false

website:
  title: 'origraph'
  site-url: https://www.origraph.net/site
  open-graph: true
  navbar:
    logo: 'logos/origraph/Logo Light Background.png'
    left:
      # - href: blog/aboutUs.qmd
      #   text: About Us
      - text: Consulting
        menu:
          - href: blog/consulting.qmd
            text: Our Approach
          - href: blog/consulting.qmd#reports-metadata-about-your-data
            text: Reports & Metadata About Your Data
          - href: blog/consulting.qmd#visual-prototyping-development
            text: Visual Prototyping & Development
          - href: blog/consulting.qmd#data-science-ai
            text: Data Science & AI
          - href: blog/consulting.qmd#system-integration-deployment
            text: System Integration & Deployment
      - href: blog.qmd
        text: Blog
    right:
      - href: blog.xml
        text: '[![RSS Logo](/logos/social/rss.svg){.origraph-icon}[RSS Feed]{.navbar-button-label}]{.origraph-button .minimal}'
      # - href: https://patreon.com/Origraph
      #   text: '[![Patreon Logo](/logos/social/patreonWhite.png){.origraph-icon}[Patreon]{.navbar-button-label}]{.origraph-button .minimal}'
      # - href: app.qmd
      #   text: '[![Application icon](/logos/ui/application.svg){.origraph-icon} Launch App]{.origraph-button}'
  back-to-top-navigation: true

format:
  html:
    include-in-header:
      text: |
        <script type="application/javascript" src="/lib/react.production.min.js"></script>
        <script type="application/javascript" src="/lib/react-dom.production.min.js"></script>
        <script type="application/javascript" src="/lib/origraph.umd.cjs"></script>
    theme:
      - minty
      - brand
    css:
      - quartoTweaks.css
      - lib/origraph.css
    toc: true
